// frontend/src/app/pages/password-recovery-token/password-recovery-token.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-password-recovery-token',
  templateUrl: './password-recovery-token.component.html',
  styleUrl: './password-recovery-token.component.css'
})
export class PasswordRecoveryTokenComponent {

}

<div class="login-recuperar">
    <div class="overlap-group-wrapper">
      <div class="overlap-group">
        <div class="rectangle"></div>
        <div class="div"></div>
        <div class="rectangle-2"></div>
        <div class="text-wrapper">Iniciar sesión</div>
        <div class="text-wrapper-2">Correo</div>
        <div class="text-wrapper-3">Contraseña</div>
        <div class="text-wrapper-4">Ingresar</div>
        <div class="text-wrapper-5">Bienvenido a nuestra app</div>
        <div class="text-wrapper-6">Olvide mi contraseña</div>
        <div class="text-wrapper-7">Aviso de privacidad</div>
        <div class="rectangle-3"></div>
        <div class="rectangle-4"></div>
        <div class="rectangle-2"></div>
        <div class="text-wrapper-8">Recuperar contraseña</div>
        <p class="p">Ingresa el código de recuperación</p>
        <div class="text-wrapper-9">Recuperar contraseña</div>
      </div>
    </div>
  </div>

// frontend-react/src/pages/PasswordRecoveryToken/PasswordRecoveryToken.tsx
import React from 'react';
import './PasswordRecoveryToken.css'; // Asegúrate de tener el archivo CSS para estilos

const LoginRecuperar: React.FC = () => {
  return (
    <div className="login-recuperar">
      <div className="overlap-group-wrapper">
        <div className="overlap-group">
          <div className="rectangle"></div>
          <div className="div"></div>
          <div className="rectangle-2"></div>
          <div className="text-wrapper">Iniciar sesión</div>
          <div className="text-wrapper-2">Correo</div>
          <div className="text-wrapper-3">Contraseña</div>
          <div className="text-wrapper-4">Ingresar</div>
          <div className="text-wrapper-5">Bienvenido a nuestra app</div>
          <div className="text-wrapper-6">Olvidé mi contraseña</div>
          <div className="text-wrapper-7">Aviso de privacidad</div>
          <div className="rectangle-3"></div>
          <div className="rectangle-4"></div>
          <div className="rectangle-2"></div>
          <div className="text-wrapper-8">Recuperar contraseña</div>
          <p className="p">Ingresa el código de recuperación</p>
          <div className="text-wrapper-9">Recuperar contraseña</div>
        </div>
      </div>
    </div>
  );
};

export default LoginRecuperar;
